name: Build OpenWrt

on:
  workflow_dispatch:  # 允许手动触发编译
  push:
    branches: [ master ]  # 指定分支有推送时触发编译
  # schedule:
  #   - cron: '0 2 * * 1'  # 可选：设置定时编译，例如每周一凌晨2点

env: # 设置一些环境变量，方便管理和修改
  REPO_URL: https://github.com/eritpchy/immortalwrt-redmi-ax3000  # 使用的OpenWrt源码仓库
  REPO_BRANCH: redmi_ax3000-24.10  # 使用的源码分支

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用较新的Ubuntu系统镜像

    steps:
    # 步骤1：检出你的仓库代码，以便工作流能访问到你的配置文件
    - name: Checkout repository
      uses: actions/checkout@v4

    # 步骤2：安装必要的系统依赖包
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply \
        python3-docutils qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl \
        unzip vim wget xmlto xxd zlib1g-dev

    # 步骤3：克隆OpenWrt源码
    - name: Clone OpenWrt source
      run: |
        git clone $REPO_URL --branch $REPO_BRANCH --depth 1 openwrt
        ls -al

    # 步骤4：更新和安装feeds（软件包列表）
    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    # 步骤5：应用你的自定义配置
    # 你可以将编译配置直接写入 .config 文件
    - name: Apply configuration
      run: |
        cd openwrt
        cat > .config <<EOF
         CONFIG_TARGET_qualcommax=y
         CONFIG_TARGET_qualcommax_ipq50xx=y

          CONFIG_IB=y
          # CONFIG_IB_STANDALONE is not set
          CONFIG_SDK=y
          CONFIG_MAKE_TOOLCHAIN=y

          CONFIG_ALL_NONSHARED=y
          CONFIG_REPRODUCIBLE_DEBUG_INFO=y

          CONFIG_PACKAGE_luci=y
        # 更多配置...
        EOF
        make defconfig


    - name: Download dependencies
      runn: |
        cd openwrt
        make -j16 download

    - name: Build tools
      run: |
        make -j$(nproc) tools/install

    - name: Build toolchain
      run: |
          make -j$(nproc) toolchain/install


    # 步骤6：开始编译（此步骤非常耗时）
    - name: Start building
      run: |
        cd openwrt
        make -j$(nproc) IGNORE_ERRORS=1
    - name: Upload bin to artifacts
      uses: actions/upload-artifact@v3
      with:
          name: bin-qualcommax-ipq50xx
          path: bin/targets/qualcommax/ipq50xx/*

    - name: Upload dl to artifacts
      uses: actions/upload-artifact@v3
      with:
          name: dl
          path: dl/*
      
  gh-pages:
    needs: [ build ]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          path: 'gh-pages'
          ref: 'gh-pages'
          fetch-depth: 0

      - name: Configure the git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Drop old versions
        run: |
          cd gh-pages
          readarray -t old_version < <(git log --format='%h' -- "${GITHUB_REF_NAME}" | tail -n +10)
          GIT_SEQUENCE_EDITOR="sed -i '1 i break'" git rebase --interactive --committer-date-is-author-date --root
          for commit in "${old_version[@]}"; do
            sed -i "/${commit}/d" .git/rebase-merge/git-rebase-todo
          done
          git rebase --continue

      - name: Download bin from artifacts
        uses: actions/download-artifact@v3
        with:
          name: bin-qualcommax-ipq50xx
          path: bin/

      - name: Copy contents
        run: |
          version="$(cat "bin/version.buildinfo")"
          mkdir -p "gh-pages/${GITHUB_REF_NAME}/${version}/"
          cp -avr bin/packages/* "gh-pages/${GITHUB_REF_NAME}/${version}/"

      - name: Commit
        run: |
          cd gh-pages
          git add .
          git commit -m "Add: ${GITHUB_REF_NAME}: $(cat ../bin/version.buildinfo)"

      - name: Publish
        run: |
          cd gh-pages
          git push -f origin gh-pages


release:
    needs: [ build ]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download dl from artifacts
        uses: actions/download-artifact@v3
        with:
          name: dl
          path: dl/

      - name: Download bin from artifacts
        uses: actions/download-artifact@v3
        with:
          name: bin-qualcommax-ipq50xx
          path: bin/targets/qualcommax/ipq50xx/

      - name: Generate release informations
        run: |
          TIME="$(curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" | jq -r .created_at)"

          TAG="ci-${GITHUB_REF_NAME}-$(date -d "${TIME}" -u +'%Y%m%d-%H%M%S-%Z')"
          echo "TAG=$TAG" >>$GITHUB_ENV

          cat <<EOF | sed -E 's/^  //' >Release.md
            CI ${GITHUB_REF_NAME} $(date -d "${TIME}" -u +'%Y-%m-%d %H:%M:%S %Z(%:z)')

            # ${GITHUB_REF_NAME}

            Build time: \`$(date -d "${TIME}" -u +'%Y-%m-%d %H:%M:%S %Z(%:z)')\`
            Release version: ${TAG}

            ## Sources
            $(cat bin/targets/qualcommax/ipq50xx/feeds.buildinfo | awk -F'[ ^]' '{printf "%s: `%s`\n", $2, $4}')

            ## SHA256
            $(cat bin/targets/qualcommax/ipq50xx/sha256sums | awk '{printf "%s: `%s`\n", $2, $1}' | sed -E 's/^\*//')
          EOF

          echo "NAME=$(head --line=1 Release.md)" >>$GITHUB_ENV
          tail --line=+2 Release.md >Body.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ env.TAG }}
          target_commitish: ${{ github.sha }}
          name: ${{ env.NAME }}
          body_path: Body.md
          files: |
            bin/targets/qualcommax/ipq50xx/sha256sums
            bin/targets/qualcommax/ipq50xx/*.*